# Generated by Django 2.1.7 on 2019-02-18 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_delete_ratings'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favourite_movies',
            field=models.ManyToManyField(related_name='favourite', to='movies.Movie'),
        ),
    ]
