# Generated by Django 2.1.7 on 2019-02-19 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190219_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favourite_movies',
        ),
    ]
