# Generated by Django 2.1.7 on 2019-02-14 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_favouritemovie_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favouritemovie',
            old_name='genre',
            new_name='Genre',
        ),
        migrations.RenameField(
            model_name='favouritemovie',
            old_name='release_date',
            new_name='Released',
        ),
        migrations.RenameField(
            model_name='favouritemovie',
            old_name='runtime',
            new_name='Runtime',
        ),
        migrations.RenameField(
            model_name='favouritemovie',
            old_name='movie_title',
            new_name='Title',
        ),
        migrations.RenameField(
            model_name='favouritemovie',
            old_name='release_year',
            new_name='Year',
        ),
    ]
