# Generated by Django 2.1.7 on 2019-02-14 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20190214_1233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favouritemovie',
            old_name='actors',
            new_name='Actors',
        ),
        migrations.RenameField(
            model_name='favouritemovie',
            old_name='awards',
            new_name='Awards',
        ),
        migrations.RenameField(
            model_name='favouritemovie',
            old_name='boxOffice',
            new_name='BoxOffice',
        ),
        migrations.RenameField(
            model_name='favouritemovie',
            old_name='country',
            new_name='Country',
        ),
        migrations.RenameField(
            model_name='favouritemovie',
            old_name='dvd',
            new_name='DVD',
        ),
        migrations.RenameField(
            model_name='favouritemovie',
            old_name='director',
            new_name='Director',
        ),
        migrations.RenameField(
            model_name='favouritemovie',
            old_name='language',
            new_name='Language',
        ),
        migrations.RenameField(
            model_name='favouritemovie',
            old_name='metascore',
            new_name='Metascore',
        ),
        migrations.RenameField(
            model_name='favouritemovie',
            old_name='plot',
            new_name='Plot',
        ),
        migrations.RenameField(
            model_name='favouritemovie',
            old_name='poster',
            new_name='Poster',
        ),
        migrations.RenameField(
            model_name='favouritemovie',
            old_name='production',
            new_name='Production',
        ),
        migrations.RenameField(
            model_name='favouritemovie',
            old_name='ratings',
            new_name='Ratings',
        ),
        migrations.RenameField(
            model_name='favouritemovie',
            old_name='response',
            new_name='Response',
        ),
        migrations.RenameField(
            model_name='favouritemovie',
            old_name='type',
            new_name='Type',
        ),
        migrations.RenameField(
            model_name='favouritemovie',
            old_name='website',
            new_name='Website',
        ),
    ]
