# Generated by Django 2.1.7 on 2019-02-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20190214_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouritemovie',
            name='Runtime',
            field=models.CharField(blank=True, max_length=255, verbose_name='Movie Runtime'),
        ),
    ]
