# Generated by Django 2.1.7 on 2019-02-17 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20190217_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Metascore',
            field=models.CharField(blank=True, max_length=5, verbose_name='Metascore'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Year',
            field=models.CharField(max_length=12, verbose_name='Movie Relase Year'),
        ),
    ]
