# Generated by Django 2.1.7 on 2019-02-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20190217_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Website',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Movie website'),
        ),
    ]
