# Generated by Django 2.1.7 on 2019-02-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_remove_movie_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Released',
            field=models.CharField(blank=True, max_length=23, verbose_name='Movie Release Date'),
        ),
    ]
