# Generated by Django 2.1.7 on 2019-02-18 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_auto_20190218_1851'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ratings',
        ),
    ]
